import Head from "next/head";
import { Inter } from "next/font/google";
import { Slide } from "@modules/slide";
import styled from "styled-components";
import "material-icons/iconfont/material-icons.css";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Home assignment - Maksymilian Kasperowicz | Storydoc</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main className={inter.className}>
        <Slide />
      </Main>
    </>
  );
}

const Main = styled.main`
  width: 100vw;
  height: 100vh;
  padding: 3rem;
  display: grid;
  gap: 4rem;
  justify-content: center;
  align-items: center;

  overflow-x: hidden;
  overflow-y: auto;
`;
